gitlab:
  webservice:
    extraEnv:
      # Configure Puma to listen on IPv6.
      BIND_IP6: "true"
    monitoring:
      # ipWhitelist: []
      expoter:
        # Configure webservice metrics listener for IPv6. 
        listenAddr: "::"
  sidekiq:
    # Configure sidekiq healthcheck and metrics listeners for IPv6. 
    # Note: Because of a known bug these services stop working on IPv4 if
    # a `::` listen address is used. Do not use this in IPv4 and dual stack
    # clusters. https://github.com/ruby/webrick/issues/99
    metrics:
      listenAddr: "::"
    health_checks:
      listenAddr: "::"
  gitlab-exporter:
    listenAddr: "::"
  spamcheck:
    listenAddr: "[::]"

nginx-ingress:
  controller:
    service:
      ipFamilyPolicy: "SingleStack" 
      ipFamilies: [ IPv6 ]
